name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  PUBLIC_IMAGE: iamtelescope/telescope-docs
  PRIVATE_IMAGE: iamtelescope/telescope-docs-private

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push public image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.PUBLIC_IMAGE }}:latest

    - name: Build and push private image with GA
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.PRIVATE_IMAGE }}:latest
        build-args: |
          ENABLE_GA=true
          GA_MEASUREMENT_ID=${{ secrets.GA_MEASUREMENT_ID }}
